-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
--
-- <leader>gg (LazyGit), <leader>up (precognition) and <leader>ow/<leader>or
-- (overseer) live on their plugin specs in lua/plugins/, so defining them
-- here too would just shadow the lazy-loading trigger.
